# Copyright (c) Facebook, Inc. and its affiliates.
# 
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# defaults:
  # - hydra/launcher: submitit_local
  # - hydra/hydra_logging: colorlog

trainer:
  trainer: ContrastiveLossTrainer
  overwrite_checkpoint: False
  batch_size: 32

  # Metric learning loss
  neg_thresh: 1.4
  pos_thresh: 0.1
  neg_weight: 1.0

  # Data loader configs
  stat_freq: 40
  lr_update_freq: 1000
  checkpoint_freq: 1000
  positive_pair_search_voxel_size_multiplier: 1.5

# Network specific configurations
net:
  model: Res16UNet34C
  weight:
  model_n_out: 32 #Feature dimension
  conv1_kernel_size: 3
  normalize_feature: True
  dist_type: L2

# Optimizer arguments
opt:
  optimizer: SGD
  max_iter: 300000
  lr: 1e-1
  momentum: 0.8
  sgd_momentum: 0.9
  sgd_dampening: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.999
  weight_decay: 1e-4
  bn_momentum: 0.05
  exp_gamma: 0.99
  scheduler: ExpLR

shape_context:
  r1: -1e9
  r2: 1e9
  nbins_xy: 1
  nbins_zy: 1
  weight_inner: False
  fast_partition: False

misc:
  out_dir: /checkpoint/jihou/checkpoints/default
  use_gpu: True
  num_gpus: 7
  lenient_weight_loading: False # Weights with the same size will be loaded

  train_num_thread: 2
  nn_max_n: 500 # The maximum number of features to find nearest neighbors in batch

  # NCE related
  nceT: 0.07
  npos: 4096
  local_rank: 0

  # TODO(s9xie): all args for scannet training
  train_limit_numpoints: 0
  data_aug_scale_min: 0.9
  data_aug_scale_max: 1.1

  cache_data: False

  ignore_label: 255
  return_transformation: False
  is_train: True

# Dataset specific configurations
data:
  dataset: ScanNetMatchPairDataset
  voxel_size: 0.025
  voxelize: False
  num_points: 40000
  scannet_match_dir: /wild6d_data/pointclouds/
  random_rotation_xyz: False
  world_space: False

# hydra:
#   run:
#     dir: ${misc.out_dir}
# #   sweep:
# #     dir: ${misc.out_dir}
#   launcher:
#     partition: debug
  #   submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  #   name: ${hydra.job.name}
    # timeout_min: 60
    # cpus_per_task: 8
    # gpus_per_node: 0
    # tasks_per_node: 1
    # mem_gb: 4
    # nodes: 1
    # max_num_timeout: 3
    # signal_delay_s: 300
